name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build application

        run: |

          docker compose build
          docker compose push

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REGISTRY_PASS }}
          repository: v-atlas/base-ci
          event-type: rebuild-instance
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  
  